name = "LaTeXDatax"
uuid = "644dedec-337d-45c6-9a86-27a5fed2b77d"
authors = ["David Gustavsson <david.e.gustavsson@gmail.com> and contributors"]

version = "3.0.0"


[deps]
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulLatexify = "45397f5d-5981-4c77-b2b3-fc36d6e9b728"

[compat]
Latexify = "0.14.7"
Unitful = "1.5"
UnitfulLatexify = "1.3.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
